services:
  mongodb:
    image: mongo:7
    container_name: sif-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: sifdb
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
